name: esp32-arduino-ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FQBN: esp32:esp32:esp32s3   # S3 için. S2 ise: esp32:esp32:esp32s2
      SKETCH: main.ino            # .ino dosyan (yol/adını gerekirse değiştir)
    steps:
      - uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Setup ESP32 Core
        run: |
          arduino-cli config init --overwrite
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile
        run: |
          arduino-cli compile \
            --fqbn "$FQBN" "$SKETCH" \
            --warnings all \
            --build-properties compiler.c.extra_flags="-Wall -Wextra -Werror" \
            --build-properties compiler.cpp.extra_flags="-Wall -Wextra -Werror" \
            --output-dir build
        

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: build
          if-no-files-found: error
