name: ros2-jazzy-lint-build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ament-lint-and-build:
    name: ament_flake8 + ament_cppcheck + ament_pyflakes + build (ROS 2 Jazzy)
    runs-on: ubuntu-24.04
    env:
      ROS_DISTRO: jazzy
      WS: .   # workspace kökün; içinde src/ olmalı
    steps:
      - uses: actions/checkout@v4

      # ROS 2 Jazzy kurulumu + linters
      - name: Install ROS 2 Jazzy and ament linters
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common curl gnupg lsb-release
          sudo mkdir -p /usr/share/keyrings
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
            http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | \
            sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y \
            ros-${ROS_DISTRO}-desktop \
            python3-colcon-common-extensions \
            python3-rosdep \
            ros-${ROS_DISTRO}-ament-flake8 \
            ros-${ROS_DISTRO}-ament-cppcheck \
            ros-${ROS_DISTRO}-ament-pyflakes \
            ros-${ROS_DISTRO}-ament-lint-auto
          sudo rosdep init || true
          rosdep update

      # Bağımlılık çözümü
      - name: rosdep install
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.sh
          rosdep install --from-paths ${WS}/src --ignore-src -r -y

      # Lintler (sadece ament linters)
      - name: Run ament linters
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.sh
          colcon test \
            --packages-select-by-dep ament_flake8 ament_cppcheck ament_pyflakes \
            --event-handlers console_direct+
          colcon test-result --verbose

      # Build
      - name: colcon build
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.sh
          colcon build --symlink-install --event-handlers console_direct+
