camera_remaps:
  rgb_image:        "/camera/camera/color/image_raw"
  depth_image:      "/camera/camera/depth/image_rect_raw"
  camera_info:      "/camera/camera/color/camera_info"
  imu:              "/camera/camera/imu"