bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_frame: odom
    default_bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.05
      max_vel_x: 0.3
      max_vel_theta: 0.6
      acc_lim_x: 1.0
      acc_lim_theta: 1.0

      critics: ["RotateToGoal","Oscillation","BaseObstacle","GoalAlign","PathAlign","PathDist","GoalDist"]
      BaseObstacle:
        scale: 0.5
      PathAlign:
        scale: 24.0
      GoalAlign:
        scale: 18.0
      PathDist:
        scale: 24.0
      GoalDist:
        scale: 18.0

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true


planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      allow_unknown: true
      tolerance: 0.25
      downsample_costmap: true

behavior_server:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_frame: odom
    server_timeout: 10.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    progress_checker:
      plugin: "nav2_behavior_tree/ProgressChecker"
    goal_checker:
      plugin: "nav2_controller/StoppedGoalChecker"
      trans_stopped_velocity: 0.05
      rot_stopped_velocity: 0.05

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    plugin_lib_names: ["wait_at_waypoint"]
    stop_on_failure: false

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      update_frequency: 10.0
      publish_frequency: 10.0
      transform_tolerance: 0.5
      footprint: "[[0.75, 0.525], [0.75, -0.525], [-0.75, -0.525], [-0.75, 0.525]]"
      footprint_padding: 0.2
      
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: realsense_pc
        realsense_pc:
          topic: "/camera/camera/depth/color/points"
          data_type: "PointCloud2"
          marking: true
          clearing: true
          obstacle_range: 6.0
          raytrace_range: 6.0
          max_obstacle_height: 2.5
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5



global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      rolling_window: false
      resolution: 0.1
      update_frequency: 2.0
      publish_frequency: 1.0
      transform_tolerance: 0.5
      footprint: "[[0.75, 0.525], [0.75, -0.525], [-0.75, -0.525], [-0.75, 0.525]]"
      footprint_padding: 0.2
      
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        topic: "/map"      # RTAB-Map’in OccupancyGrid topic'i (çoğu durumda /map)
        map_subscribe_transient_local: true
        subscribe_to_updates: true
        track_unknown_space: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.8

  global_costmap_client:
    ros__parameters:
      use_sim_time: false
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

